openapi: 3.0.1
info:
  title: Back-end Challenge 2021
  description: CRUD Users
  version: 0.1
servers:
  url: http://localhost:8080/

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  responses:
    UnauthorizedError:
      description: API key não está presente no header
      headers:
        WWW_Authenticate:
          schema:
            type: string

security:
  ApiKeyAuth: []

paths:
  /:
    get:
      summary: Retorna uma mensagem com o nome do projeto
      responses:
        '200':
          description: OK
  /users:
    get:
      summary: Retorna uma lista de usuários.
      responses:
        '200':    
          description: Um array JSON com os dados de todos os usuários presentes
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '401':
          $ref: "#/components/responses/UnauthorizedError"
    post:
      summary: Cria um usuário.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses: 
        '201':
          description: Created
        '400':
          description: JSON inválido e incompatível com o objeto User
        '401':
          $ref: "#/components/responses/UnauthorizedError"
    put:
      summary: Atualiza um usuário.
      requestBody:
        
  /users/{userId}:
    get:
      summary: Retorna um usuário pelo ID.
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type : integer
            format: int64
            minimum: 1
      responses: 
        '200':
          description: OK
        '401':
          $ref: "#/components/responses/UnauthorizedError"